package:
  name: ros-noetic-tf2-server
  version: 1.1.2
source:
  git_url: https://github.com/peci1/tf2_server-release.git
  git_rev: release/noetic/tf2_server/1.1.2-1
  folder: ros-noetic-tf2-server/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 16
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - gtest
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
    - ros-noetic-geometry-msgs
    - ros-noetic-message-generation
    - ros-noetic-message-runtime
    - ros-noetic-nodelet
    - ros-noetic-roscpp
    - ros-noetic-rostest
    - ros-noetic-tf
    - ros-noetic-tf2-msgs
    - ros-noetic-tf2-ros
    - setuptools
  run:
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-geometry-msgs
    - ros-noetic-message-runtime
    - ros-noetic-nodelet
    - ros-noetic-roscpp
    - ros-noetic-rospy
    - ros-noetic-tf2-msgs
    - ros-noetic-tf2-ros
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
