package:
  name: ros-noetic-cras-topic-tools
  version: 2.3.3
source:
  git_url: https://gitlab.fel.cvut.cz/cras/ros-release/ros-utils.git
  git_rev: release/noetic/cras_topic_tools/2.3.3-1
  folder: ros-noetic-cras-topic-tools/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 16
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - boost
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
    - ros-noetic-cras-cpp-common
    - ros-noetic-cras-msgs
    - ros-noetic-geometry-msgs
    - ros-noetic-nodelet
    - ros-noetic-rosbag
    - ros-noetic-roscpp
    - ros-noetic-roslaunch
    - ros-noetic-roslint
    - ros-noetic-rostest
    - ros-noetic-rostopic
    - ros-noetic-std-msgs
    - ros-noetic-topic-tools
  run:
    - boost
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-cras-cpp-common
    - ros-noetic-cras-msgs
    - ros-noetic-cras-py-common
    - ros-noetic-nodelet
    - ros-noetic-rosbag
    - ros-noetic-roscpp
    - ros-noetic-rospy
    - ros-noetic-std-msgs
    - ros-noetic-topic-tools
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
