package:
  name: ros-noetic-point-cloud-transport
  version: 1.0.11
source:
  git_url: https://gitlab.fel.cvut.cz/cras/ros-release/point_cloud_transport.git
  git_rev: release/noetic/point_cloud_transport/1.0.11-1
  folder: ros-noetic-point-cloud-transport/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 16
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
    - ros-noetic-cras-cpp-common
    - ros-noetic-cras-topic-tools
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-message-filters
    - ros-noetic-message-generation
    - ros-noetic-message-runtime
    - ros-noetic-nodelet
    - ros-noetic-pluginlib
    - ros-noetic-roscpp
    - ros-noetic-roslint
    - ros-noetic-sensor-msgs
    - ros-noetic-topic-tools
    - setuptools
  run:
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-cras-cpp-common
    - ros-noetic-cras-py-common
    - ros-noetic-cras-topic-tools
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-message-filters
    - ros-noetic-message-runtime
    - ros-noetic-nodelet
    - ros-noetic-pluginlib
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-topic-tools
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
