package:
  name: ros-noetic-magnetometer-compass
  version: 1.0.3
source:
  git_url: https://gitlab.fel.cvut.cz/cras/ros-release/compass.git
  git_rev: release/noetic/magnetometer_compass/1.0.3-1
  folder: ros-noetic-magnetometer-compass/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 16
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - geographiclib-cpp
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-angles
    - ros-noetic-catkin
    - ros-noetic-compass-msgs
    - ros-noetic-cras-cpp-common
    - ros-noetic-geometry-msgs
    - ros-noetic-imu-transformer
    - ros-noetic-message-filters
    - ros-noetic-nodelet
    - ros-noetic-roscpp
    - ros-noetic-roslib
    - ros-noetic-sensor-msgs
    - ros-noetic-tf2
    - ros-noetic-tf2-geometry-msgs
    - ros-noetic-tf2-ros
  run:
    - geographiclib-cpp
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-compass-msgs
    - ros-noetic-geometry-msgs
    - ros-noetic-imu-transformer
    - ros-noetic-message-filters
    - ros-noetic-nodelet
    - ros-noetic-roscpp
    - ros-noetic-roslib
    - ros-noetic-sensor-msgs
    - ros-noetic-tf2
    - ros-noetic-tf2-geometry-msgs
    - ros-noetic-tf2-ros
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
