package:
  name: ros-noetic-cras-cpp-common
  version: 2.3.3
source:
  git_url: https://gitlab.fel.cvut.cz/cras/ros-release/ros-utils.git
  git_rev: release/noetic/cras_cpp_common/2.3.3-1
  folder: ros-noetic-cras-cpp-common/src/work
  patches:
    - patch/ros-noetic-cras-cpp-common.patch

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 16
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - boost
    - eigen
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-bondcpp
    - ros-noetic-catkin
    - ros-noetic-class-loader
    - ros-noetic-diagnostic-msgs
    - ros-noetic-diagnostic-updater
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-filters
    - ros-noetic-geometry-msgs
    - ros-noetic-nodelet
    - ros-noetic-pluginlib
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-rosgraph-msgs
    - ros-noetic-roslaunch
    - ros-noetic-roslint
    - ros-noetic-rostest
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-tf2
    - ros-noetic-tf2-eigen
    - ros-noetic-tf2-geometry-msgs
    - ros-noetic-tf2-ros
    - ros-noetic-tf2-sensor-msgs
    - ros-noetic-topic-tools
    - urdfdom_headers
  run:
    - boost
    - eigen
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-bondcpp
    - ros-noetic-class-loader
    - ros-noetic-diagnostic-msgs
    - ros-noetic-diagnostic-updater
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-filters
    - ros-noetic-geometry-msgs
    - ros-noetic-nodelet
    - ros-noetic-pluginlib
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-tf2
    - ros-noetic-tf2-ros
    - ros-noetic-topic-tools
    - urdfdom_headers
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
