package:
  name: ros-noetic-dynamic-robot-state-publisher
  version: 1.2.0
source:
  git_url: https://github.com/peci1/dynamic_robot_state_publisher-release.git
  git_rev: release/noetic/dynamic_robot_state_publisher/1.2.0-1
  folder: ros-noetic-dynamic-robot-state-publisher/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 16
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - sel(linux64): sysroot_linux-64 2.17
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - cython
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-kdl-parser
    - ros-noetic-robot-state-publisher
    - ros-noetic-roscpp
    - ros-noetic-rostest
    - ros-noetic-sensor-msgs
  run:
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-kdl-parser
    - ros-noetic-robot-state-publisher
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
